### ISSUE TITLE
Won't load the seed I input

### ISSUE THREAD

**Issue by haroelim** [FlooflesDev/LCSeedPicker#10]
Hello, when I input a seed, the game still ends up generating a new seed instead of loading the seed I inputted

**Comment by FlooflesDev** [comment]
I can look at this later today, I thought this worked when I tested it but I might be wrong.

Could you please send me a list of mods that you are using? It is very likely that another mod is overwriting the seed that you set

**Comment by haroelim** [comment]
Sure

BepInEx-BepInExPack-5.4.2100
RugbugRedfern-Skinwalkers-4.0.1
CapyCat-Solos_Ring_Compass-1.0.3
AlexCodesGames-AdditionalSuits-2.0.0
x753-More_Suits-1.4.1
Verity-TooManySuits-1.0.5
x753-Mimics-2.3.2
anormaltwig-LateCompany-1.0.10
notnotnotswipez-MoreCompany-1.7.6
tinyhoot-ShipLoot-1.0.0
thomas-AlwaysShowClock-1.0.0
TheFluff-FairAI-1.3.2
Rune580-LethalCompany_InputUtils-0.6.1
Renegades-FlashlightToggle-1.5.0
Renegades-WalkieUse-1.5.0
2018-LC_API-3.4.5
EliteMasterEric-Coroner-1.5.3
CapyCat-Solos_Bodycams-1.0.5
MoreLethal-Pinger-3.2.0
boxofbiscuits97-QuotaRollover-2.3.0
Bobbie-MetalRecharging-1.0.0
Coomfy-CoomfyDungeon-1.0.12
amnsoft-EmployeeAssignments-1.1.0
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.0
MegaPiggy-BuyableShotgun-1.0.4
MegaPiggy-BuyableShotgunShells-1.0.5
matsuura-HealthMetrics-1.0.2
Toskan4134-LethalRegeneration-1.2.0
Stoneman-LethalProgression-1.3.2
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
MikeMediaStudios-MikesTweaks-2.0.2
MoonJuice-BuyRateSettings-1.3.1
Sligili-HDLethalCompany-1.5.6
akechii-DiscountAlert-2.3.0
Ozone-Runtime_Netcode_Patcher-0.2.5
AlexCodesGames-AdditionalContentFramework-1.0.3
HomelessGinger-MaskedEnemyOverhaul-3.1.1
ATK-LaterNights-0.9.1
Ozone-BepInUtils-1.2.1
Ozone-Glow_Steps-1.1.2
Pooble-LCBetterSaves-1.7.3
CTMods-KarmaForBeingAnnoying-1.1.0
zerouni-CustomRadio-0.1.1
rafl-CustomBoomboxMusicFixed-1.0.2
Mom_Llama-Lethal_Company_Enhancer-0.1.10
sunnobunno-YippeeMod-1.2.3
Azim-HoarderBud-1.0.10
blink9803-AutoFlyToCompany-1.0.1
darksnakex-NoCorpseHigherQuota-2.5.0
IntegrityChaos-Diversity-1.1.10
Suskitech-AlwaysHearActiveWalkies-1.4.4
FlipMods-TooManyEmotes-1.8.3
AllToasters-SpectateEnemies-2.2.1
Blorb-WeatherMultipliers-1.1.0
Sv_Matt-HideModList-1.0.1
PortableNavi-BetterInverseTeleporter-1.0.2
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
SkrimpGang-AAAAAGHH-1.0.1
darmuh-ghostCodes-1.5.1
F4ilS4fe-MaskTheDead-1.0.5
Dev1A3-ScannableCodes-1.0.2
ButteryStancakes-AccurateStaminaDisplay-1.1.2
OE_Tweaks-Possessed_Masks-2.0.2
extraes-LethalLoudnessMeter-1.0.2
ZG-ScalingStartCredits-1.0.6
Electric131-IsThisTheWayICame-1.1.4
SoraYuki-ShowAmmoCount-1.1.0
MaxWasUnavailable-MoonOfTheDay-1.0.4
Sligili-More_Emotes-1.3.3
Rattenbonkers-Teleporter_Cooldown_Reset-1.0.1
TwinDimensionalProductions-CoilHeadStare-1.0.3
FlipMods-ObjectVolumeController-1.0.4
eXish-Batteries-1.0.4
AgentRev-ShootableMouthDogs-1.0.1
CyanBlob-Motion_Tracker-1.0.0
ScruffyRules-BatteryText-1.0.0
CTMods-ChatCommands-1.1.7
FlooflesDEV-LCSeedPicker-1.2.1

**Comment by haroelim** [comment]
I could try it on a very basic modpack (just the seedpicker installed) to see if that changes anything, too

Edit: I tried the mod by itself, and it *did* load the random seed I typed. I have suspicions of which mods might be messing with your mod, I'll report back if I find out

**Comment by haroelim** [comment]
I have found the conflicting mod: it is MaxWasUnavailable-MoonOfTheDay-1.0.4

When that mod is disabled in my modpack, that seedpicker works as intended. When it is enabled, the seedpicker is ignored

**Comment by MaxWasUnavailable** [comment]
Crossposting from the issue on my end:

https://github.com/MaxWasUnavailable/MoonOfTheDay/issues/3#issuecomment-1927527876

Should be an easy fix if you set your patch priority to run last @FlooflesDev

**Comment by FlooflesDev** [comment]
> Crossposting from the issue on my end:
> 
> [MaxWasUnavailable/MoonOfTheDay#3 (comment)](https://github.com/MaxWasUnavailable/MoonOfTheDay/issues/3#issuecomment-1927527876)
> 
> Should be an easy fix if you set your patch priority to run last @FlooflesDev

I was hoping that Harmony had a function like that, but I had some trouble finding it until now. Thanks for the help and for letting me loosely copy your mod :) (extremely new to Unity modding).
I fixed the issue in v1.2.2 of the mod.
