### ISSUE TITLE
[FEATURE REQUEST] Show Current Seed

### ISSUE THREAD

**Issue by Matt-662607015** [FlooflesDev/LCSeedPicker#6]
I've noticed the game shows the current seed when landing, but not long enough to write it down. It would be really helpful if LCSeedPicker would display the current seed in the escape menu.

**Comment by FlooflesDev** [comment]
This is a nice feature that I'd love to add. Whenever I have time I will look into it!
I'm not sure if it is possible to show the seed to all players. Currently, I only show the seed display for the host.
I hope that displaying it for the host is good enough for now?

**Comment by FlooflesDev** [comment]
@Matt-662607015 I managed to add the feature and it's now on thunderstore. Let me know if there are any issues :)
